name: Agregar Informaci칩n 游늷
description: Agrega mas perfiles a la Web.
title: "[Info] "
labels: ["info"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## 游닇 Llena los detalles a continuaci칩n"

  - type: input
    id: title
    attributes:
      label: "游늷 T칤tulo"
      description: "Escribe un t칤tulo corto y descriptivo No repetido."
      placeholder: "Ejemplo: Nombre de Empresa o Pol칤tico"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "游닇 Descripci칩n"
      description: "Explica los detalles que ser치n mostrados en el art칤culo."
      placeholder: "Escribe aqu칤 la informaci칩n..."
    validations:
      required: true

  - type: textarea
    id: fuentes
    attributes:
      label: "游댕 Fuentes"
      description: "A침ade enlaces a fuentes confiables (ejemplo: noticias, documentos oficiales)."
      placeholder: "Ejemplo:\n- https://ejemplo.com/fuente1\n- https://ejemplo.com/fuente2"
    validations:
      required: true
